version: '3.7'
services:
  js-service:
    container_name: js_test
    build: 
      context: ./
      target: dev
    volumes:
      - '.:/src'
    ports: 
      - "3000:3000"
    command: > 
      bash -c "npm install && npm run dev"
    environment: 
      NODE_ENV: development

